config/routes.rb
Course2::Application.routes.draw do

  root 'posts#index'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
    resources :comments, only: [:create, :index]
  end

  resources :categories, only: [:create, :new, :edit, :update, :show]
  resources :users, only: [:show, :edit, :update]

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, through: :post_categories
  has_many :post_categories

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'

  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  
  has_many :comments
  has_many :categories, through: :post_categories
  has_many :post_categories

  has_many :votes

  validates :title, presence: true
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 5 }


  def total_votes
    self.up_votes - self.down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  has_secure_password
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  # makes controller method use also in view template

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]   
    # otherwise find(nil)
  end
  # memorization (minor performance optimization)
  # cases call multiple times in one template, hit db once

  def logged_in?
    !!current_user  # makes it true or false only
  end

  def require_user
    if !logged_in?
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, except: [:show]
  before_action :set_category, only: [:show, :edit, :update]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  
  def create    
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
  before_action :require_user, except: [:index, :show]

  def index
    @posts = Post.all.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      redirect_to @post #
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post #
    else
      render 'edit'
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :description, :category_ids => [])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.where(username: params[:username]).take

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id   # save user_id to session
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil   # remove user_id from session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_user, only: [:edit, :update]

  def new
  end

  def create
    @user = User.new(username: params[:username], password: params[:password], password_confirmation: params[:password])

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def http_url(url)
    if url.include?('http://')
      url
    else
      ('http://').concat(url)
    end
  end

  def show_time(d)
    d.strftime("at %H:%M, %F") if d
  end
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

<%= render 'shared/errors', obj: @category %>

<div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <p><%= f.submit %></p>
</div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Category' %>
<%= render 'form' %>

<p><%= link_to 'Back', category_path %></p>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'New Category' %>
<%= render 'form' %>

<p><%= link_to 'Back', posts_path %></p>

app/views/categories/show.html.erb
<%= render 'shared/content_title', title: "Category: #{@category.name}" %>

<p><%= link_to 'Back', posts_path %>
  | <%= link_to 'Edit', edit_category_path %></p>

<% if @category.posts.any? %> 
  <%= render @category.posts %>
<% end %>

app/views/comments/_comment.html.erb
<div class="comment-box">
  "<%= comment.body %>"<br>
  by <%= link_to comment.creator.username, user_path(comment.creator) %> (at <small><%= comment.created_at %></small>)
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Course2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
<%= render 'shared/header' %>
  <%= yield %>
  
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

<%= render 'shared/errors', obj: @post %>

<div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 3 %>
  </div>

  <%= collection_check_boxes(:post, :category_ids, Category.all, :id, :name) do |b| %>
    <%= b.label() { b.check_box + b.text } %>
  <% end %>
  <p><%= f.submit %></p>
  
</div>
<% end %>

app/views/posts/_post.html.erb
<div class="post-box"> 

  <%= post.total_votes %>
  <%= link_to "up", vote_post_path(post, vote: true), method: 'post' %>
  <%= link_to "down", vote_post_path(post, vote: false), method: 'post' %>

  <% if post.categories.any? %>
    <% post.categories.each do |category| %>
      <small>| <%= link_to category.name, category_path(category) %></small>
    <% end %><small> |</small><br>
  <% end %>  
  <p>
    <strong><%= post.title %></strong> <small><%= link_to "#{post.comments.count} comments", post_path(post) %></small><br>
    <small><%= link_to post.url, http_url(post.url) %></small>
  </p>
  <p><%= post.description %><br>

  by <%= link_to post.creator.username, user_path(post.creator) %> (<small><%= show_time(post.created_at) %></small>)</p>
  
  <p><%= link_to 'Back', posts_path %>
  | <%= link_to 'Edit', edit_post_path(post) %></p>
  
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Post' %>

<%= render 'form' %>

<p><%= link_to 'Back', post_path %></p>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>
<% if @posts.any? %>
  <%= render @posts %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'New Post' %>

<%= render 'form' %>

<p><%= link_to 'Back', posts_path %></p>

app/views/posts/show.html.erb
<% if @post.categories.any? %>
  <% @post.categories.each do |category| %>
    <small>| <%= link_to category.name, category_path(category) %></small>
  <% end %><small> |</small><br>
<% end %>  
<%= render 'shared/content_title', title: "Post: #{@post.title}" %>

  <p>
    <strong><%= link_to @post.url, http_url(@post.url) %></strong><br>
    <%= @post.description %>
  </p>
  <p>
    by <%= link_to @post.creator.username, user_path(@post.creator) %>
    <small><%= "(#{show_time(@post.created_at)})" %></small>
  </p>

<p><%= link_to 'Back', posts_path %>
  | <%= link_to 'Edit', edit_post_path %></p>

<% if logged_in? %>
  <div class="comment-box">
    <%= form_for [@post, @comment] do |f| %>
      <%= render 'shared/errors', obj: @comment %>
    
      <div class="field">
        <%= f.label :body, 'Leave a Comment:' %><br>
        <%= f.text_area :body, rows: 3 %>
      </div>
      <p><%= f.submit %></p>
    <% end %>
  </div>
<% end %>

<% if @post.comments.any? %>
  <%= render @post.comments %>
<% end %>

app/views/shared/_content_title.html.erb
<h1><%= title %><hr></h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="error_messages">
  <h2>these are error messages. Please try again.</h2>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<% if logged_in? %>
<p><%= link_to 'Profile', user_path(current_user) %>
| <%= link_to 'New Post', new_post_path %> 
| <%= link_to 'New Category', new_category_path %>
| <%= link_to 'log out', logout_path %></p>
<% else %>
<p><%= link_to 'log in', login_path %>
| <%= link_to 'register', register_path %></p>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Profile' %>

<%= form_for @user do |f| %>
  <p><%= f.label :username %>
    <%= f.text_field :username %></p>
  <p><%= f.label :password %><br>
    <%= f.password_field :password %></p>
  <p><%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %></p>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register here' %>

<%= form_tag '/register' do %>
  <p><%= label_tag :username %><br>
    <%= text_field_tag :username %></p>
  <p><%= label_tag :password %><br>
    <%= password_field_tag :password %></p>
  <%= submit_tag 'register' %>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>
<p><%= link_to 'Back', posts_path %>
  | <%= link_to 'Edit', edit_user_path %></p>

<% if @user.posts.any? %>
  <p>Posts</p>
  <%= render @user.posts %>
<% end %>

<% if @user.comments.any? %>
  <p>Comments</p>
  <%= render @user.comments %>
<% end %>